# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

sudo: required

# For testing against and using RcppRedis
services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libhiredis-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r rmarkdown
  - ./travis-tool.sh install_r rredis
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package hadley/testthat
  # need the package itself as a dependency of rrlite!
  - R CMD INSTALL .
  - # ./travis-tool.sh github_package ropensci/rrlite
  - Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="http://cran.rstudio.com")); devtools::install_git("https://github.com/ropensci/rrlite", args="--recursive")'

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

# after_success:
#   - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
